Importing Libraries

In [1]:
import numpy as np;
import pandas as pd;
import tensorflow as tf;

2023-12-11 16:34:01.061413: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-11 16:34:01.932743: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-11 16:34:03.056278: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-11 16:34:03.056306: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-11 16:34:03.586148: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

In [4]:
A = np.ones([3,3]);
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
B = np.zeros([4,4])
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
C = np.random.random([3,3])
C

array([[0.68325868, 0.62225066, 0.83776728],
       [0.65042786, 0.52655713, 0.05865464],
       [0.08418901, 0.69107456, 0.98460471]])

In [50]:
D = A * C;
D

print("D.Shape", np.array(D).shape)

D.Shape (3, 3)


In [67]:
d = np.array(D)
print(d.shape)
exd = d.reshape(-1,9)
print(exd.shape)
exd

(3, 3)
(1, 9)


array([[0.68325868, 0.62225066, 0.83776728, 0.65042786, 0.52655713,
        0.05865464, 0.08418901, 0.69107456, 0.98460471]])